server:
  port: 8089
  undertow:
    buffer-size: 16384
    buffers-per-region: 20
    io-threads: 64
    worker-threads: 512
    direct-buffers: true

#Ports defined in TDS_Build:docker-compose.yml
exam-results-transmitter-service:
  session-url: http://localhost:32842
  assessment-url: http://localhost:32841
  exam-url: http://localhost:8081