#Configure the Spring Actuator endpoints to require an authenticated user with the MANAGEMENT role
management:
  security:
    roles: MANAGEMENT

---
spring:
  profiles: local-development
  #Port defined in TDS_Build:docker-compose.yml
  rabbitmq:
    port: 32846
  datasource:
    jdbcUrl: ${sbac.jdbc.host}/exam_audit
    username: ${sbac.jdbc.user}
    password: ${sbac.jdbc.password}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: false

flyway:
  enabled: true
  url: ${sbac.jdbc.host}/exam_audit
  user: ${sbac.jdbc.user}
  password: ${sbac.jdbc.password}

server:
  port: 8089
  undertow:
    buffer-size: 16384
    io-threads: 64
    worker-threads: 512
    direct-buffers: true

#Ports defined in TDS_Build:docker-compose.yml
exam-results-transmitter-service:
  session-url: http://localhost:32842
  assessment-url: http://localhost:32841
  exam-url: http://localhost:80
  tis-url: ${sbac.tis.url}
  tis-callback-url: ${sbac.tis.callback.url}
  validate-trt-xml: false
  send-to-tis: false

oauth:
  tis-client-id: ${oauth.tis.client.id}
  tis-client-secret: ${oauth.tis.client.secret}
  tis-username: ${oauth.tis.username}
  tis-password: ${oauth.tis.password}
  access-url: ${oauth.access.url}

